version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cinema
      - POSTGRES_USER=cinema_user
      - POSTGRES_PASSWORD=cinema_pass
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=cinema
      - DB_USER=cinema_user
      - DB_PASSWORD=cinema_pass
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
  static_volume:
  media_volume:
